### ISSUE TITLE
安装的时候报错~

### ISSUE THREAD

**Issue by lycciam** [bluedazzle/django-simple-serializer#5]
执行pip install django-simple-serializer
的时候，报错如下：

Collecting django-simple-serializer
  Downloading django-simple-serializer-2.0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Administrator\AppData\Local\Temp\pip-build-8awkwv3a\django-simple-serializer\setup.py", line 21, in <module>
        LONG_DESCRIPTION = read("README.rst")
      File "C:\Users\Administrator\AppData\Local\Temp\pip-build-8awkwv3a\django-simple-serializer\setup.py", line 12, in read
        return codecs.open(os.path.join(os.path.dirname(__file__), fname)).read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 112: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Administrator\AppData\Local\Temp\pip-build-8awkwv3a\django-simple-serializer\

环境为python3.4.3~
祝顺利~

**Comment by long2ice** [comment]
我也是

**Comment by teavamc** [comment]
我也是...最后直接下载了源文件..
然后解压,在解压文件中找到src文件夹
把readme.rst中的内容全部清空....
再复制文件目录,打开cmd控制台
输入cd 粘贴目录
直接python setup.py install
就可以了

**Comment by idotial** [comment]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 110: ordinal not in range(128)
我pip安装的时候报了这个错，也是一样的吧，这要怎么搞啊

**Comment by idotial** [comment]
我在ubuntu环境下报的，结果应该是locale设置的问题

**Comment by luopangda** [comment]
更新：安装之后还需要把 dss 和 django_simple_serializer.egg-info,两个文件夹 复制到site-packages.
_______________________________________________________________________________________________
@teavmac 谢谢，我用你的方法，下载源码，清空README.rst 里的内容，还是报同样的错。
后来我把这个文件删了，重新建一个空的README.rst，就好使了

**Comment by panzer596000** [comment]
这个是因为读取README.rst时的编码问题，setup.py文件中函数read修改一下就好了
`def read(fname):
    return codecs.open(os.path.join(os.path.dirname(__file__), fname),encoding='utf-8').read()`
指定编码格式utf-8
